# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
