# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20161219_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registertime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=32)),
                ('Originaltime', models.IntegerField()),
                ('Sendcount', models.IntegerField()),
            ],
        ),
    ]
