# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20161222_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='utime',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
