# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_article_utime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='utime',
            field=models.IntegerField(max_length=32),
        ),
    ]
