# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20161222_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imgdescription',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
