# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_article_imgdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='web_url',
            field=models.URLField(max_length=32, null=True),
        ),
    ]
