# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_article_web_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='utime',
            field=models.IntegerField(),
        ),
    ]
