# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20161224_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imgdescription',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
