# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_article_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='registered_time',
            field=models.DateTimeField(auto_now_add=True, default=1980),
            preserve_default=False,
        ),
    ]
