# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_userinfo_ctime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='ctime',
            new_name='rtime',
        ),
    ]
