# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_auto_20161224_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='rtime',
            field=models.TimeField(),
        ),
    ]
