# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_auto_20161224_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='rtime',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='field',
            field=models.DateField(null=True),
        ),
    ]
