# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_auto_20161224_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='field',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='admin_type',
            field=models.BooleanField(default=False),
        ),
    ]
