# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_favor'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='favor_count',
            field=models.IntegerField(default=0),
        ),
    ]
