# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_auto_20161227_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64)),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Article')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='o', to='app01.Comment')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Userinfo')),
            ],
        ),
    ]
